
///////////////////////////////////////////////////////////////////////////////
// File Name: altsqrt_varianceCalc.v
// Megafunction Name(s):
//          ALTSQRT
//
// Simulation Library Files(s):
//          altera_mf
///////////////////////////////////////////////////////////////////////////////
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 15.1.0 Build 185 10/21/2015 SJ Lite Edition
// ************************************************************

// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions
// and other software and tools, and its AMPP partner logic
// functions, and any output files from any of the foregoing
// (including device programming or simulation files), and any
// associated documentation or information are expressly subject
// to the terms and conditions of the Altera Program License
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other
// applicable license agreement, including, without limitation,
// that your use is for the sole purpose of programming logic
// devices manufactured by Altera and sold by Altera or its
// authorized distributors.  Please refer to the applicable
// agreement for further details.

module altsqrt_varianceCalc (
    input  wire        clk,
    input  wire [43:0] radical,
    output wire [21:0] q,
    output wire [22:0] remainder
);

    // Internal wires connecting to the ALTSQRT megafunction
    wire [21:0] sub_wire0;
    wire [22:0] sub_wire1;

    // Instantiate the ALTSQRT megafunction
    altsqrt #(
        .pipeline     (11),
        .q_port_width (22),
        .r_port_width (23),
        .width        (44),
        .lpm_type     ("ALTSQRT")
    ) ALTSQRT_component (
        .clk       (clk),
        .radical   (radical),
        .q         (sub_wire0),
        .remainder (sub_wire1)
    );

    // Drive the top-level outputs
    assign q        = sub_wire0;
    assign remainder = sub_wire1;

endmodule
