# Quartus Prime Pin Assignments TCL Script
# Generated from vj.csv

set_location_assignment PIN_U2 -to LED_config_finished
set_location_assignment PIN_AC4 -to LED_dll_locked
set_location_assignment PIN_Y14 -to btn_capture
set_location_assignment PIN_J1 -to clk_50
set_location_assignment PIN_AE9 -to faceBox_done
set_location_assignment PIN_AE15 -to ii_gen_done
set_location_assignment PIN_Y15 -to measure_performance
set_location_assignment PIN_AH12 -to ov7670_data[7]
set_location_assignment PIN_AG12 -to ov7670_data[6]
set_location_assignment PIN_AA14 -to ov7670_data[5]
set_location_assignment PIN_AC15 -to ov7670_data[4]
set_location_assignment PIN_Y12 -to ov7670_data[3]
set_location_assignment PIN_AA12 -to ov7670_data[2]
set_location_assignment PIN_AF15 -to ov7670_data[1]
set_location_assignment PIN_AF14 -to ov7670_data[0]
set_location_assignment PIN_AB14 -to ov7670_href
set_location_assignment PIN_AH14 -to ov7670_pclk
set_location_assignment PIN_G5 -to ov7670_pwdn
set_location_assignment PIN_E22 -to ov7670_reset
set_location_assignment PIN_AB2 -to ov7670_sioc
set_location_assignment PIN_U1 -to ov7670_siod
set_location_assignment PIN_AD14 -to ov7670_vsync
set_location_assignment PIN_AH22 -to ov7670_xclk
set_location_assignment PIN_AG14 -to slide_sw_RESET
set_location_assignment PIN_J27 -to slide_sw_capture_mode
set_location_assignment PIN_J28 -to slide_sw_resend_reg_values
set_location_assignment PIN_P2 -to subwin_done
set_location_assignment PIN_AE5 -to vga_CLK
set_location_assignment PIN_AC10 -to vga_b[7]
set_location_assignment PIN_AE14 -to vga_b[6]
set_location_assignment PIN_AD15 -to vga_b[5]
set_location_assignment PIN_AG11 -to vga_b[4]
set_location_assignment PIN_AB10 -to vga_b[3]
set_location_assignment PIN_AE13 -to vga_b[2]
set_location_assignment PIN_AC14 -to vga_b[1]
set_location_assignment PIN_AH11 -to vga_b[0]
set_location_assignment PIN_AB13 -to vga_blank_N
set_location_assignment PIN_AB15 -to vga_g[7]
set_location_assignment PIN_AE16 -to vga_g[6]
set_location_assignment PIN_AC11 -to vga_g[5]
set_location_assignment PIN_AA16 -to vga_g[4]
set_location_assignment PIN_AE17 -to vga_g[3]
set_location_assignment PIN_AF16 -to vga_g[2]
set_location_assignment PIN_AD11 -to vga_g[1]
set_location_assignment PIN_AB16 -to vga_g[0]
set_location_assignment PIN_AD12 -to vga_hsync
set_location_assignment PIN_AA13 -to vga_r[7]
set_location_assignment PIN_AC12 -to vga_r[6]
set_location_assignment PIN_AH18 -to vga_r[5]
set_location_assignment PIN_AG19 -to vga_r[4]
set_location_assignment PIN_Y13 -to vga_r[3]
set_location_assignment PIN_AB12 -to vga_r[2]
set_location_assignment PIN_AG18 -to vga_r[1]
set_location_assignment PIN_AH19 -to vga_r[0]
set_location_assignment PIN_L23 -to vga_sync_N
set_location_assignment PIN_AB11 -to vga_vsync